"""Pydantic schemas package for EnnovateX AI Platform.

This package contains all request and response schemas for the API endpoints.
"""

# Text processing schemas
from .text_schemas import (
    TextSummarizationRequest,
    TextSummarizationResponse,
    QuestionAnsweringRequest,
    QuestionAnsweringResponse,
    BatchTextRequest,
    BatchTextResponse,
    BatchTextResult,
    BatchStats,
    ReadabilityMetrics,
    KeyPhrase,
    TextAnalysis,
    ModelInfo,
    ServiceStats,
    ServiceConfig,
    TextServiceStatsResponse,
    HealthCheckResponse,
)

# Image processing schemas
from .image_schemas import (
    ImageUploadRequest,
    ImageUploadResponse,
    ImageCaptioningRequest,
    ImageCaptioningResponse,
    VisualQuestionAnsweringRequest,
    VisualQuestionAnsweringResponse,
    BatchImageRequest,
    BatchImageResponse,
    BatchImageResult,
    BatchImageStats,
    ImageDescriptionRequest,
    ImageDescriptionResponse,
    ImageProperties,
    ImageModelInfo,
    ImageServiceStats,
    ImageServiceConfig,
    ImageServiceStatsResponse,
    ImageHealthCheckResponse,
)

# Audio processing schemas
from .audio_schemas import (
    AudioUploadRequest,
    AudioUploadResponse,
    SpeechToTextRequest,
    SpeechToTextResponse,
    AudioTranslationRequest,
    AudioTranslationResponse,
    BatchAudioRequest,
    BatchAudioResponse,
    BatchAudioResult,
    BatchAudioStats,
    SupportedLanguage,
    SupportedLanguagesResponse,
    WordTimestamp,
    AudioProperties,
    AudioModelInfo,
    AudioServiceStats,
    AudioServiceConfig,
    AudioServiceStatsResponse,
    AudioHealthCheckResponse,
)

# Health check and system monitoring schemas
from .healthcheck_schemas import (
    PingResponse,
    SystemStatusResponse,
    ReadinessResponse,
    SystemMetricsResponse,
    ComprehensiveHealthResponse,
    SystemResources,
    GPUInfo,
    ModelStatus,
    ServiceHealth,
    DatabaseHealth,
    ExternalServiceHealth,
    ReadinessCheck,
    MetricsSnapshot,
    AlertInfo,
    HealthCheckConfig,
    MaintenanceInfo,
)

__all__ = [
    # Text schemas
    "TextSummarizationRequest",
    "TextSummarizationResponse",
    "QuestionAnsweringRequest",
    "QuestionAnsweringResponse",
    "BatchTextRequest",
    "BatchTextResponse",
    "BatchTextResult",
    "BatchStats",
    "ReadabilityMetrics",
    "KeyPhrase",
    "TextAnalysis",
    "ModelInfo",
    "ServiceStats",
    "ServiceConfig",
    "TextServiceStatsResponse",
    "HealthCheckResponse",
    
    # Image schemas
    "ImageUploadRequest",
    "ImageUploadResponse",
    "ImageCaptioningRequest",
    "ImageCaptioningResponse",
    "VisualQuestionAnsweringRequest",
    "VisualQuestionAnsweringResponse",
    "BatchImageRequest",
    "BatchImageResponse",
    "BatchImageResult",
    "BatchImageStats",
    "ImageDescriptionRequest",
    "ImageDescriptionResponse",
    "ImageProperties",
    "ImageModelInfo",
    "ImageServiceStats",
    "ImageServiceConfig",
    "ImageServiceStatsResponse",
    "ImageHealthCheckResponse",
    
    # Audio schemas
    "AudioUploadRequest",
    "AudioUploadResponse",
    "SpeechToTextRequest",
    "SpeechToTextResponse",
    "AudioTranslationRequest",
    "AudioTranslationResponse",
    "BatchAudioRequest",
    "BatchAudioResponse",
    "BatchAudioResult",
    "BatchAudioStats",
    "SupportedLanguage",
    "SupportedLanguagesResponse",
    "WordTimestamp",
    "AudioProperties",
    "AudioModelInfo",
    "AudioServiceStats",
    "AudioServiceConfig",
    "AudioServiceStatsResponse",
    "AudioHealthCheckResponse",
    
    # Health check schemas
    "PingResponse",
    "SystemStatusResponse",
    "ReadinessResponse",
    "SystemMetricsResponse",
    "ComprehensiveHealthResponse",
    "SystemResources",
    "GPUInfo",
    "ModelStatus",
    "ServiceHealth",
    "DatabaseHealth",
    "ExternalServiceHealth",
    "ReadinessCheck",
    "MetricsSnapshot",
    "AlertInfo",
    "HealthCheckConfig",
    "MaintenanceInfo",
]