[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = {
  ENVIRONMENT = "production",
  DEBUG = "false",
  LOG_LEVEL = "info",
  WORKERS = "4",
  MAX_WORKERS = "8",
  WORKER_TIMEOUT = "300",
  KEEP_ALIVE = "2",
  MAX_REQUESTS = "1000",
  MAX_REQUESTS_JITTER = "100"
}

[environments.staging]
variables = {
  ENVIRONMENT = "staging",
  DEBUG = "true",
  LOG_LEVEL = "debug",
  WORKERS = "2",
  MAX_WORKERS = "4"
}

# Health check configuration
[healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3

# Resource limits
[resources]
cpu = 1000  # 1 vCPU
memory = 1024  # 1GB RAM

# Networking
[networking]
serviceDomain = "ennovatex-api"

# Database and Redis will be configured as Railway services
# and connected via environment variables:
# DATABASE_URL (PostgreSQL)
# REDIS_URL (Redis)